"""add metric variant analysis_run summary tables and missing columns

Revision ID: 7d771e25734d
Revises: c86f6e48b842
Create Date: 2026-08-08 17:39:19.272846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7d771e25734d'
down_revision: Union[str, Sequence[str], None] = '7f97f1b852fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysis_run_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_run_task_id'), ['task_id'], unique=False)

    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('UP', 'DOWN', 'NEUTRAL', name='metric_direction'), nullable=False),
    sa.Column('type', sa.Enum('BINARY', 'CONTINUOUS', name='metric_type'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_guardrail', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_type'), ['type'], unique=False)

    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variant_name'), ['name'], unique=False)

    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('summary')
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variant_name'))

    op.drop_table('variant')
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_type'))
        batch_op.drop_index(batch_op.f('ix_metric_name'))
        batch_op.drop_index(batch_op.f('ix_metric_direction'))

    op.drop_table('metric')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_task_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_run_status'))

    op.drop_table('analysis_run')
    # ### end Alembic commands ###
