"""empty message

Revision ID: 7f97f1b852fe
Revises: 2cecfc48c257
Create Date: 2026-07-29 20:29:09.008692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7f97f1b852fe'
down_revision: Union[str, Sequence[str], None] = '2cecfc48c257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.alter_column('hypothesis',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('unit_of_randomization',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('unit_of_randomization',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hypothesis',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
